source 'https://github.com/CocoaPods/Specs.git'

target 'myLib1', :exclusive => true do
  pod "myLib1", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "myLib1", :path => "../"

  
end
